fix: enable gemm layer in ncnn
- Required by convolution layer (x86/int8 optimizations) to avoid linker errors
- Fixes 'undefined reference to ncnn::Gemm_x86_utility::pack_A_tile_int8' in Ubuntu build
- Likely fixes Windows build failure as well